spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v11?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
