spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v11?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
     host: 192.168.52.130
     port: 6379
     password: zzp
     jedis:
       pool:
         max-active: 66

dubbo:
  application:
    name: user__service
  registry:
    protocol: zookeeper
    address: 192.168.52.130:2181
  protocol:
    port: 28812

server:
  port: 8083
