dubbo:
  application:
    name: search__web
  registry:
    protocol: zookeeper
    address: 192.168.52.130:2181
server:
  port: 9092

spring:
   rabbitmq:
      host: 192.168.52.130
      port: 5672
      username: zzp
      password: zzp
      virtual-host: /zzp
