dubbo:
  application:
    name: sso_web
  registry:
    protocol: zookeeper
    address: 192.168.52.130:2181

server:
  port: 9095


spring:
  redis:
    host: 192.168.52.130
    port: 6379
    password: zzp
    jedis:
      pool:
        max-active: 66
  thymeleaf:
    cache: false
