dubbo:
  application:
    name: common--service
  registry:
    protocol: zookeeper
    address: 192.168.52.130:2181
  protocol:
    port: 28813

spring:
  mail:
    host: smtp.qq.com
    username: 2493360725@qq.com
    password: kkjixwrgflqueacf
    default-encoding: utf-8
  rabbitmq:
      host: 192.168.52.130
      port: 5672
      username: zzp
      password: zzp
      virtual-host: /zzp

mail:
    fromAddress: 2493360725@qq.com

server:
  port: 8083

